spring.application.name=hrdtestWithSts

# DataSource ??
spring.datasource.url=jdbc:mariadb://localhost:3306/hirdtestfinal
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# MyBatis ??
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.kim.hrdtest.employees.domain
mybatis.configuration.map-underscore-to-camel-case=true

# ?? ?? (??)
logging.level.com.kim.employees.mapper=debug
# ?? ?? (??)
server.port=8080

# Thymeleaf ?? (??? ??)
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML

# favicon 404 ?? ?? ????
spring.mvc.log-resolved-exception=false